### PR TITLE
Fixed several errors in 2 LREC feature extractors/tests

### LINKED ISSUE #129: WordConjunctionOneTwoThreeGramWindowTwo causes ArrayIndexOutOfBoundsException
`WordConjunctionOneTwoThreeGramWindowTwo` causes `ArrayIndexOutOfBoundsException`.  The following code can be used to reproduce the issue:

```java
WordConjunctionOneTwoThreeGramWindowTwo wordconj = new WordConjunctionOneTwoThreeGramWindowTwo("WordConj3GramWin2");
TextAnnotation ta = TextAnnotationUtilities.createFromTokenizedString("I give John $900 today .");
Constituent c = ta.getView(ViewNames.TOKENS).getConstituentsCoveringSpan(3, 4).get(0);
wordconj.getFeatures(c);
```
Error caused by line 71 in `WordConjunctionOneTwoThreeGramWindowTwo`. Looks like `PosWordConjunctionSizeTwoWindowSizeTwo` have the same problem.

### PR DESCRIPTION
**Pull request by christos-c**
- Fixed a logic error that was causing an out of bounds exception when tested with token indices > window size.
- Also fixed the logic of the `WordConjunctionOneTwoThreeGramWindowTwo` extractor since it was only reporting up to 2grams _(this was a problem in the original LBJ code)_.
- Also fixed the logic of the `PosWordConjunctionSizeTwoWindowSizeTwo` since the word/pos conjunctions were wrong (also only returned 1grams instead of 2grams). _(this was a problem in the original LBJ code)_
- Fixed the unit test for both of these and updated them to use JUnit 4 and `DummyTextAnnotationGenerator`

Closes #129

@danyaljj @mssammon please check the code really carefully and make sure you get someone to fix the other feature extractors.

### CODE REVIEW

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java [hunk 1]
```diff
@@ -44,8 +37,7 @@ public PosWordConjunctionSizeTwoWindowSizeTwo(String viewName) {
         this.viewName = viewName;
     }
 
-    public String[] getwindowkfrom(View TOKENS, int startspan, int endspan, int k) {
-
+    private String[] getwindowkfrom(View TOKENS, int startspan, int endspan, int k) {
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: Camel case?

Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: Not my code, but ok!

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java [hunk 2]
```diff
@@ -12,29 +12,22 @@
...
-
-import java.io.File;
-import java.io.FileWriter;
-import java.io.BufferedWriter;
-import java.io.IOException;
+import java.util.LinkedHashSet;
+import java.util.Set;
 
 /**
+ * Extracts the POS Tags as well as the form (text) of tokens 2 before and 2 after from
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: k before and k after?

Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: No, this is not a generic extractor. Look at the name.

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java [hunk 3]
```diff
@@ -44,8 +37,7 @@ public PosWordConjunctionSizeTwoWindowSizeTwo(String viewName) {
         this.viewName = viewName;
     }
 
-    public String[] getwindowkfrom(View TOKENS, int startspan, int endspan, int k) {
-
+    private String[] getWindowK(View TOKENS, int startspan, int endspan, int k) {
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: could you add comment for `@param k`?

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java [hunk 4]
```diff
@@ -58,32 +50,32 @@ public PosWordConjunctionSizeTwoWindowSizeTwo(String viewName) {
             startwin = 0;
         }
 
+        int index = 0;
         for (int i = startwin; i < endwin; i++) {
-
-            window[i] = TOKENS.getConstituentsCoveringSpan(i, i + 1).get(0).getSurfaceForm();
+            window[index] = TOKENS.getConstituentsCoveringSpan(i, i + 1).get(0).getSurfaceForm();
+            index++;
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: drop new line?

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java [hunk 5]
```diff
@@ -12,29 +12,22 @@
...
+ * the given token and generates a discrete feature from it.
  *
- * @author Paul Vijayakumar, Mazin Bokhari Extracts the POS Tags as well as the form (text) of
- *         tokens 2 before and 2 after from the given token and generates a discrete feature from
- *         it.
- *
+ * @keywords pos-tagger, words, tokens, window
+ * @author Paul Vijayakumar, Mazin Bokhari, Christos Christodoulopoulos
  */
 public class PosWordConjunctionSizeTwoWindowSizeTwo implements FeatureExtractor {
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: `SizeTwo` twice intentional?

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java [hunk 6]
```diff
@@ -12,24 +12,22 @@
...
-import edu.illinois.cs.cogcomp.edison.features.RealFeature;
-import edu.illinois.cs.cogcomp.edison.features.helpers.SpanLabelsHelper;
 import edu.illinois.cs.cogcomp.edison.utilities.EdisonException;
 
-import java.util.*;
+import java.util.LinkedHashSet;
+import java.util.Set;
 
 /**
+ * Extracts the k Tokens to the left and k Tokens to the right of the Constituent object.
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java]: tokens, lowercase?

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java (hunk 5 above)
Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: You're a coauthor on the paper that established this convention, I'm not going to answer that :)

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java [hunk 7]
```diff
@@ -85,50 +82,50 @@ public WordConjunctionOneTwoThreeGramWindowTwo(String viewName) {
...
                     if (context != 0) {
                         f.append("_");
                     }
                     f.append(forms[i + context]);
                 }
 
-                __id = classifier + ":" + (i + "_" + j);
-                __value = "(" + (f.toString()) + ")";
-                __result.add(new DiscreteFeature(__id + __value));
+                // 2 is the center object in the array so i should go from -2 to +2
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java]: 0 is the center?

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java (hunk 5 above)
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: Maybe make it a little more clear, cause it's confusing in this form; how about: `PosWordConjunctionTwoGramWindowTwo`

Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: Actually I'm not if it makes it more clear ...

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java [hunk 8]
```diff
@@ -66,10 +63,10 @@ public WordConjunctionOneTwoThreeGramWindowTwo(String viewName) {
             startwin = 0;
         }
 
+        int index = 0;
         for (int i = startwin; i < endwin; i++) {
-
-            window[i] = TOKENS.getConstituentsCoveringSpan(i, i + 1).get(0).getSurfaceForm();
-
+            window[index] = TOKENS.getConstituentsCoveringSpan(i, i + 1).get(0).getSurfaceForm();
```
Comment (danyaljj) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java]: So the size of `window` is `2k+1`, while the number of elements we put inside it is `endwin - startwin = endspan + k - (startspan - k) = 2k + endspan - startspan`, which can be bigger than `2k+1`?

File: edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java [hunk 9]
```diff
@@ -10,111 +10,61 @@
...
 import java.util.Set;
-import java.util.Random;
-import java.io.Writer;
 
-import org.apache.log4j.Logger;
+import static org.junit.Assert.assertTrue;
+import static org.junit.Assert.fail;
 
 /**
  * Test class for SHALLOW PARSER Formpp Feature Extractor
```
Comment (danyaljj) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: POS?

Comment (christos-c) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: No that's for the chunker.

Comment (danyaljj) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: ah used in chunker? But like for a user of Edison, no one care where it's used; right? And I don't know what is "Formpp" ...

Comment (christos-c) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: I shouldn't have to answer that either... you read the paper. (we need to report this because it's important to know which features were used to replicate each system)

Comment (danyaljj) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: What I'm saying is that, the description is not clear.

Comment (christos-c) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: Make a suggestion

Comment (danyaljj) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: How about: 
```
Unit test for {@link PosWordConjunctionSizeTwoWindowSizeTwo} extractor, which generates a conjunction of 3-shingles from a window of 2 tokens. The extractor is originally used in illinois-chunker (shallow parser). 
```

Comment (christos-c) [inline edison/src/test/java/edu/illinois/cs/cogcomp/edison/features/lrec/TestPosWordConjunctionSizeTwoWindowSizeTwo.java]: Cool -- added.

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java (hunk 4 above)
Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: done

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java (hunk 7 above)
Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java]: yes, added a note

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java (hunk 6 above)
Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java]: done

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java (hunk 3 above)
Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/PosWordConjunctionSizeTwoWindowSizeTwo.java]: done

File: edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java (hunk 8 above)
Comment (christos-c) [inline edison/src/main/java/edu/illinois/cs/cogcomp/edison/features/lrec/WordConjunctionOneTwoThreeGramWindowTwo.java]: We assume that the span of the current constituent is 1 (hence the 2k+1). If this was a general feature extractor I would change it to `2k+(constEnd-constStart)`, but this is fine.

**Comment by danyaljj** [comment]
Merging!

**Comment by christos-c** [comment]
@danyaljj @mssammon keep in mind that the other tests and feature extractors are not tested or fixed. Someone (not an undergrad) should do this.
