### PR TITLE
fixing the lazy initialization for the quantifier.

### LINKED ISSUE #327: Lazy initialization for quantifier
Verify that the initialization of [the quantifier annotator](https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/quantifier/src/main/java/edu/illinois/cs/cogcomp/quant/driver/Quantifier.java) is properly done in a "lazy" way.

### PR DESCRIPTION
**Pull request by danyaljj**
Closes #327

### CODE REVIEW

File: quantifier/src/main/java/edu/illinois/cs/cogcomp/quant/driver/Quantifier.java [hunk 1]
```diff
@@ -44,7 +44,9 @@
     }
 
     public Quantifier() {
-        super(ViewNames.QUANTITIES, new String[0]);
+        // lazily initialize by default.
+        this(true);
+
         normalizer = new Normalizer();
```
Comment (mssammon) [inline quantifier/src/main/java/edu/illinois/cs/cogcomp/quant/driver/Quantifier.java]: shouldn't these go either in the initalize() method or the other constructor?

Comment (danyaljj) [inline quantifier/src/main/java/edu/illinois/cs/cogcomp/quant/driver/Quantifier.java]: done.
